[2024-12-09T20:41:45.573+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-09T20:41:45.587+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_data_pipeline_mongodb_complex.branch_task manual__2024-12-09T20:41:33.882109+00:00 [queued]>
[2024-12-09T20:41:45.593+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_data_pipeline_mongodb_complex.branch_task manual__2024-12-09T20:41:33.882109+00:00 [queued]>
[2024-12-09T20:41:45.594+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-09T20:41:45.603+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): branch_task> on 2024-12-09 20:41:33.882109+00:00
[2024-12-09T20:41:45.610+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=771) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-09T20:41:45.611+0000] {standard_task_runner.py:72} INFO - Started process 773 to run task
[2024-12-09T20:41:45.612+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_data_pipeline_mongodb_complex', 'branch_task', 'manual__2024-12-09T20:41:33.882109+00:00', '--job-id', '312', '--raw', '--subdir', 'DAGS_FOLDER/etl_data_pipeline_mongodb_complex.py', '--cfg-path', '/tmp/tmp0hbde9oy']
[2024-12-09T20:41:45.613+0000] {standard_task_runner.py:105} INFO - Job 312: Subtask branch_task
[2024-12-09T20:41:45.830+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_data_pipeline_mongodb_complex.branch_task manual__2024-12-09T20:41:33.882109+00:00 [running]> on host 8553af9ff67b
[2024-12-09T20:41:45.888+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_data_pipeline_mongodb_complex' AIRFLOW_CTX_TASK_ID='branch_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-09T20:41:33.882109+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-09T20:41:33.882109+00:00'
[2024-12-09T20:41:45.889+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-09T20:41:45.889+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-09T20:41:45.890+0000] {logging_mixin.py:190} INFO - Current task name:branch_task state:running start_date:2024-12-09 20:41:45.587686+00:00
[2024-12-09T20:41:45.890+0000] {logging_mixin.py:190} INFO - Dag name:etl_data_pipeline_mongodb_complex and current dag run status:running
[2024-12-09T20:41:45.891+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-09T20:41:45.891+0000] {baseoperator.py:416} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-12-09T20:41:45.898+0000] {python.py:240} INFO - Done. Returned value was: load_data
[2024-12-09T20:41:45.899+0000] {branch.py:38} INFO - Branch into load_data
[2024-12-09T20:41:45.900+0000] {skipmixin.py:230} INFO - Following branch ('load_data',)
[2024-12-09T20:41:45.907+0000] {skipmixin.py:278} INFO - Skipping tasks [('skip_load', -1)]
[2024-12-09T20:41:45.929+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-09T20:41:45.930+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_data_pipeline_mongodb_complex, task_id=branch_task, run_id=manual__2024-12-09T20:41:33.882109+00:00, execution_date=20241209T204133, start_date=20241209T204145, end_date=20241209T204145
[2024-12-09T20:41:45.937+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-09T20:41:45.938+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-09T20:41:45.938+0000] {logging_mixin.py:190} INFO - Dag name:etl_data_pipeline_mongodb_complex queued_at:2024-12-09 20:41:33.893261+00:00
[2024-12-09T20:41:45.939+0000] {logging_mixin.py:190} INFO - Task hostname:8553af9ff67b operator:BranchPythonOperator
[2024-12-09T20:41:45.987+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-09T20:41:46.154+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-09T20:41:46.158+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
