[2024-12-07T20:07:26.789+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-07T20:07:26.807+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_branch_python_operator_decorator.ext_py_d scheduled__2024-12-06T00:00:00+00:00 [queued]>
[2024-12-07T20:07:26.817+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_branch_python_operator_decorator.ext_py_d scheduled__2024-12-06T00:00:00+00:00 [queued]>
[2024-12-07T20:07:26.818+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-07T20:07:26.829+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonExternalDecoratedOperator): ext_py_d> on 2024-12-06 00:00:00+00:00
[2024-12-07T20:07:26.839+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=227) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-07T20:07:26.841+0000] {standard_task_runner.py:72} INFO - Started process 232 to run task
[2024-12-07T20:07:26.841+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'example_branch_python_operator_decorator', 'ext_py_d', 'scheduled__2024-12-06T00:00:00+00:00', '--job-id', '219', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_branch_operator_decorator.py', '--cfg-path', '/tmp/tmp2t1rr_6n']
[2024-12-07T20:07:26.842+0000] {standard_task_runner.py:105} INFO - Job 219: Subtask ext_py_d
[2024-12-07T20:07:26.885+0000] {task_command.py:467} INFO - Running <TaskInstance: example_branch_python_operator_decorator.ext_py_d scheduled__2024-12-06T00:00:00+00:00 [running]> on host 8553af9ff67b
[2024-12-07T20:07:26.964+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_branch_python_operator_decorator' AIRFLOW_CTX_TASK_ID='ext_py_d' AIRFLOW_CTX_EXECUTION_DATE='2024-12-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-06T00:00:00+00:00'
[2024-12-07T20:07:26.966+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-07T20:07:26.966+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-07T20:07:26.967+0000] {logging_mixin.py:190} INFO - Current task name:ext_py_d state:running start_date:2024-12-07 20:07:26.808389+00:00
[2024-12-07T20:07:26.967+0000] {logging_mixin.py:190} INFO - Dag name:example_branch_python_operator_decorator and current dag run status:running
[2024-12-07T20:07:26.967+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-07T20:07:27.342+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python /tmp/venv-call1gw5kwib/script.py /tmp/venv-call1gw5kwib/script.in /tmp/venv-call1gw5kwib/script.out /tmp/venv-call1gw5kwib/string_args.txt /tmp/venv-call1gw5kwib/termination.log
[2024-12-07T20:07:27.344+0000] {process_utils.py:190} INFO - Output:
[2024-12-07T20:07:28.844+0000] {process_utils.py:194} INFO - /home/***/.local/lib/python3.12/site-packages/***/configuration.py:859 FutureWarning: section/key [core/sql_alchemy_conn] has been deprecated, you should use[database/sql_alchemy_conn] instead. Please update your `conf.get*` call to use the new name
[2024-12-07T20:07:29.928+0000] {process_utils.py:194} INFO - doing something in external Python
[2024-12-07T20:07:30.418+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-07T20:07:30.431+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-07T20:07:30.432+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=example_branch_python_operator_decorator, task_id=ext_py_d, run_id=scheduled__2024-12-06T00:00:00+00:00, execution_date=20241206T000000, start_date=20241207T200726, end_date=20241207T200730
[2024-12-07T20:07:30.444+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-07T20:07:30.444+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-07T20:07:30.445+0000] {logging_mixin.py:190} INFO - Dag name:example_branch_python_operator_decorator queued_at:2024-12-07 20:07:06.968261+00:00
[2024-12-07T20:07:30.445+0000] {logging_mixin.py:190} INFO - Task hostname:8553af9ff67b operator:_PythonExternalDecoratedOperator
[2024-12-07T20:07:30.468+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-07T20:07:30.493+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-07T20:07:30.496+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-09T20:10:15.940+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-09T20:10:15.973+0000] {taskinstance.py:2603} INFO - Dependencies not met for <TaskInstance: example_branch_python_operator_decorator.ext_py_d scheduled__2024-12-06T00:00:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-12-09T20:10:15.994+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
