[2024-12-03T14:04:34.678+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-03T14:04:34.704+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_data_pipeline_mongodb.load_data manual__2024-12-03T13:58:08.870853+00:00 [queued]>
[2024-12-03T14:04:34.717+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_data_pipeline_mongodb.load_data manual__2024-12-03T13:58:08.870853+00:00 [queued]>
[2024-12-03T14:04:34.718+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-03T14:04:34.743+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2024-12-03 13:58:08.870853+00:00
[2024-12-03T14:04:34.755+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=256) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-03T14:04:34.758+0000] {standard_task_runner.py:72} INFO - Started process 268 to run task
[2024-12-03T14:04:34.760+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_data_pipeline_mongodb', 'load_data', 'manual__2024-12-03T13:58:08.870853+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/etl_data_pipeline_mongodb.py', '--cfg-path', '/tmp/tmp60zk09kc']
[2024-12-03T14:04:34.761+0000] {standard_task_runner.py:105} INFO - Job 181: Subtask load_data
[2024-12-03T14:04:34.826+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_data_pipeline_mongodb.load_data manual__2024-12-03T13:58:08.870853+00:00 [running]> on host ed9532b68cd8
[2024-12-03T14:04:34.960+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_data_pipeline_mongodb' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T13:58:08.870853+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-03T13:58:08.870853+00:00'
[2024-12-03T14:04:34.962+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-03T14:04:34.963+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-03T14:04:34.963+0000] {logging_mixin.py:190} INFO - Current task name:load_data state:running start_date:2024-12-03 14:04:34.705694+00:00
[2024-12-03T14:04:34.964+0000] {logging_mixin.py:190} INFO - Dag name:etl_data_pipeline_mongodb and current dag run status:running
[2024-12-03T14:04:34.964+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-03T14:04:35.045+0000] {logging_mixin.py:190} INFO - Données chargées dans MongoDB, collection 'cleaned_data'
[2024-12-03T14:04:35.047+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-03T14:04:35.061+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-03T14:04:35.062+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_data_pipeline_mongodb, task_id=load_data, run_id=manual__2024-12-03T13:58:08.870853+00:00, execution_date=20241203T135808, start_date=20241203T140434, end_date=20241203T140435
[2024-12-03T14:04:35.080+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-03T14:04:35.080+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-03T14:04:35.081+0000] {logging_mixin.py:190} INFO - Dag name:etl_data_pipeline_mongodb queued_at:2024-12-03 13:58:08.952796+00:00
[2024-12-03T14:04:35.082+0000] {logging_mixin.py:190} INFO - Task hostname:ed9532b68cd8 operator:PythonOperator
[2024-12-03T14:04:35.134+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-03T14:04:35.157+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T14:04:35.162+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
