[2024-12-09T20:51:34.607+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-09T20:51:34.622+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_data_pipeline_mongodb_complex.load_data manual__2024-12-09T20:40:46.043807+00:00 [queued]>
[2024-12-09T20:51:34.629+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_data_pipeline_mongodb_complex.load_data manual__2024-12-09T20:40:46.043807+00:00 [queued]>
[2024-12-09T20:51:34.630+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-12-09T20:51:34.640+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_data> on 2024-12-09 20:40:46.043807+00:00
[2024-12-09T20:51:34.647+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=992) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-09T20:51:34.649+0000] {standard_task_runner.py:72} INFO - Started process 994 to run task
[2024-12-09T20:51:34.649+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_data_pipeline_mongodb_complex', 'load_data', 'manual__2024-12-09T20:40:46.043807+00:00', '--job-id', '333', '--raw', '--subdir', 'DAGS_FOLDER/etl_data_pipeline_mongodb_complex.py', '--cfg-path', '/tmp/tmpgu38hksb']
[2024-12-09T20:51:34.650+0000] {standard_task_runner.py:105} INFO - Job 333: Subtask load_data
[2024-12-09T20:51:34.899+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_data_pipeline_mongodb_complex.load_data manual__2024-12-09T20:40:46.043807+00:00 [running]> on host 8553af9ff67b
[2024-12-09T20:51:34.957+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_data_pipeline_mongodb_complex' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-09T20:40:46.043807+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-09T20:40:46.043807+00:00'
[2024-12-09T20:51:34.959+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-09T20:51:34.959+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-09T20:51:34.960+0000] {logging_mixin.py:190} INFO - Current task name:load_data state:running start_date:2024-12-09 20:51:34.623356+00:00
[2024-12-09T20:51:34.960+0000] {logging_mixin.py:190} INFO - Dag name:etl_data_pipeline_mongodb_complex and current dag run status:running
[2024-12-09T20:51:34.961+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-09T20:51:35.001+0000] {logging_mixin.py:190} INFO - Données chargées dans MongoDB.
[2024-12-09T20:51:35.002+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-09T20:51:35.012+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-09T20:51:35.012+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_data_pipeline_mongodb_complex, task_id=load_data, run_id=manual__2024-12-09T20:40:46.043807+00:00, execution_date=20241209T204046, start_date=20241209T205134, end_date=20241209T205135
[2024-12-09T20:51:35.019+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-09T20:51:35.019+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-09T20:51:35.020+0000] {logging_mixin.py:190} INFO - Dag name:etl_data_pipeline_mongodb_complex queued_at:2024-12-09 20:40:46.050932+00:00
[2024-12-09T20:51:35.020+0000] {logging_mixin.py:190} INFO - Task hostname:8553af9ff67b operator:PythonOperator
[2024-12-09T20:51:35.065+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-09T20:51:35.214+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-09T20:51:35.217+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
