[2024-12-09T21:02:10.190+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-09T21:02:10.203+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_data_pipeline_mongodb_complex.branch_task manual__2024-12-09T21:01:59.078708+00:00 [queued]>
[2024-12-09T21:02:10.209+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_data_pipeline_mongodb_complex.branch_task manual__2024-12-09T21:01:59.078708+00:00 [queued]>
[2024-12-09T21:02:10.211+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-09T21:02:10.240+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): branch_task> on 2024-12-09 21:01:59.078708+00:00
[2024-12-09T21:02:10.247+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=152) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-09T21:02:10.249+0000] {standard_task_runner.py:72} INFO - Started process 154 to run task
[2024-12-09T21:02:10.249+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_data_pipeline_mongodb_complex', 'branch_task', 'manual__2024-12-09T21:01:59.078708+00:00', '--job-id', '355', '--raw', '--subdir', 'DAGS_FOLDER/etl_data_pipeline_mongodb_complex.py', '--cfg-path', '/tmp/tmpt77xy8w3']
[2024-12-09T21:02:10.250+0000] {standard_task_runner.py:105} INFO - Job 355: Subtask branch_task
[2024-12-09T21:02:10.296+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_data_pipeline_mongodb_complex.branch_task manual__2024-12-09T21:01:59.078708+00:00 [running]> on host 90de14a479be
[2024-12-09T21:02:10.546+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_data_pipeline_mongodb_complex' AIRFLOW_CTX_TASK_ID='branch_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-09T21:01:59.078708+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-09T21:01:59.078708+00:00'
[2024-12-09T21:02:10.548+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-09T21:02:10.548+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-09T21:02:10.549+0000] {logging_mixin.py:190} INFO - Current task name:branch_task state:running start_date:2024-12-09 21:02:10.203705+00:00
[2024-12-09T21:02:10.549+0000] {logging_mixin.py:190} INFO - Dag name:etl_data_pipeline_mongodb_complex and current dag run status:running
[2024-12-09T21:02:10.550+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-09T21:02:10.550+0000] {baseoperator.py:416} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-12-09T21:02:10.558+0000] {python.py:240} INFO - Done. Returned value was: load_data
[2024-12-09T21:02:10.558+0000] {branch.py:38} INFO - Branch into load_data
[2024-12-09T21:02:10.559+0000] {skipmixin.py:230} INFO - Following branch ('load_data',)
[2024-12-09T21:02:10.566+0000] {skipmixin.py:278} INFO - Skipping tasks [('skip_load', -1)]
[2024-12-09T21:02:10.614+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-09T21:02:10.615+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_data_pipeline_mongodb_complex, task_id=branch_task, run_id=manual__2024-12-09T21:01:59.078708+00:00, execution_date=20241209T210159, start_date=20241209T210210, end_date=20241209T210210
[2024-12-09T21:02:10.627+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-09T21:02:10.628+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-09T21:02:10.628+0000] {logging_mixin.py:190} INFO - Dag name:etl_data_pipeline_mongodb_complex queued_at:2024-12-09 21:01:59.094001+00:00
[2024-12-09T21:02:10.629+0000] {logging_mixin.py:190} INFO - Task hostname:90de14a479be operator:BranchPythonOperator
[2024-12-09T21:02:10.664+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-09T21:02:10.831+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-09T21:02:10.844+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
